### PR TITLE
A few enhancements

### PR DESCRIPTION
**Pull request by aloxe**
I faced a few problems while installing and configuring the plugin on grav. I think the following changes will fix them and make the plugin more user friendly. 
- request for jQuery
- space left around calendar ics urls
- find correct URL for proxy.php even when grav isn't installed at the root
- error when language not set
- legend always displayed
Each change is on a separate commit.

### CODE REVIEW

**Comment by wernerjoss** [comment]
@aloxe : 
thanks for taking the time to improve this plugin :+1: 
I just created a new release (0.2.11) BEFORE I saw your pull request, so that is not already in 0.2.11.
from what I saw so far, your changes look fine.
I will now try the result and create another new release when everyting is ok, but let you know before.

**Comment by wernerjoss** [comment]
... as commented, I'm back again:
the automatic CORS Url detection from your patch did not work for me, see attached screenshot.
so I decided to do this using getAbsolutePath() - then it is ok.
please check/comment.
grafik

**Comment by aloxe** [comment]
The problem with `getAbsolutePath()` is it is using the url of the current page to find the plugin path and this only works when the calendar page is not nested. If you move your test calendar in a folder, it will not find the right proxy url.

In your screenshot I see that in your test `linktags` doesn't grab the `<link rel="stylesheet">` from the plugin which doesn't look normal. Is it in the page code header?

**Comment by wernerjoss** [comment]
Am Mittwoch, 3. November 2021, 22:20:47 CET schrieb aloxe:
> The problem with `getAbsolutePath()` is it is using the url of the current
> page to find the plugin path and this only works when the calendar page is
> not nested. If you move your test calendar in a folder, it will not find
> the right proxy url.

ah, ok - I never checked this use case as I never needed it...

> In your screenshot I see that in your test `linktags` doesn't grab the
> `<link rel="stylesheet">` from the plugin which doesn't look normal. Is it
> in the page code header?

no, there is no `<link rel="stylesheet">` anywhwere.
only
`<link href="/werner/assets/a1e31bdeef14373592e770c3e9f0ae28.css" type="text/css" rel="stylesheet">`

**Comment by wernerjoss** [comment]
Am Freitag, 5. November 2021, 09:51:34 CET schrieb Werner Joss:
> no, there is no `<link rel="stylesheet">` anywhwere.
> only
> `<link href="/werner/assets/a1e31bdeef14373592e770c3e9f0ae28.css"> type="text/css" rel="stylesheet">`

well, I mean, the mentioned line is in the page header, yes.

**Comment by aloxe** [comment]
So @wernerjoss  that works for you too right?

**Comment by wernerjoss** [comment]
Am Freitag, 5. November 2021, 12:52:11 CET schrieb aloxe:
> So @wernerjoss  that works for you too right?

no, it is just as I show in my screenshot before.
ATM it can be seen on my live site at https://hoernerfranzracing.de/werner/kalender
including some console.log() statements.
I'll let it in this state until tomorrow morning for reference, then I will restore again my version with
getAbsolutePath() which works for me :-)

**Comment by wernerjoss** [comment]
FYI, I have now changed the code on my live site,
so you can see in console see why linktagurl is not working, but the page does not crash

**Comment by aloxe** [comment]
> no, it is just as I show in my screenshot before. ATM it can be seen on my live site at https://hoernerfranzracing.de/werner/kalender including some console.log() statements. I'll let it in this state until tomorrow morning for reference, then I will restore again my version with getAbsolutePath() which works for me :-)

What I can see is that your calendar is not loading the css stylesheet that comes with the plugin. I guess this is a use case we should take into account. I'll work on something that passes {{ base_url_absolute }} to the DOM, I thing we can't avoid it.

**Comment by wernerjoss** [comment]
Am Samstag, 6. November 2021, 16:13:48 CET schrieb aloxe:
> What I can see is that your calendar is not loading the css stylesheet that
> comes with the plugin. 

well, my theme combines all css into one file.

> I guess this is a use case we should take into
> account. 

yes, sure.

> I'll work on something that passes {{ base_url_absolute }} to the
> DOM, I thing we can't avoid it.

I have done that in git master, works for me here.
 (code still needs formatting, though)
please check / compare with what you intend to do.

**Comment by aloxe** [comment]
> Am Samstag, 6. November 2021, schrieb  wernerjoss:

> I have done that in git master, works for me here. (code still needs formatting, though) please check / compare with what you intend to do.

This is exactly what I intended to do (except using the twig variable). Since your example was still having CORS API URL in 404. I submitted PR  #37 to fix it.

**Pull request merged**
