### PR TITLE
use {{ base_url_absolute }} and fix path for proxy.php

### PR DESCRIPTION
**Pull request by aloxe**
I fixed the path to the proxy that was missing "user". Also I preferred to simplify `fullcalendar.php` and use the twig variable for the base url.

### CODE REVIEW

**Comment by aloxe** [comment]
@wernerjoss wrote:
> ok for the path fix :-) but where does base_url_absolute come from ? (I don't see where this is computed ...)

This is one of the available [theme variable](https://learn.getgrav.org/17/themes/theme-vars#base-url-absolute-variable) provided by twig.

**Comment by aloxe** [comment]
today, @wernerjoss wrote:
> ok for the path fix :-) but where does base_url_absolute come from ? (I don't see where this is computed ...)

This is one of the [theme variable](https://learn.getgrav.org/17/themes/theme-vars#base-url-absolute-variable) provided by Twig.

**Comment by aloxe** [comment]
This is one of the theme variable provided by Twig
https://learn.getgrav.org/17/themes/theme-vars#base-url-absolute-variable

**Comment by wernerjoss** [comment]
> This is one of the theme variable provided by Twig https://learn.getgrav.org/17/themes/theme-vars#base-url-absolute-variable

ah, ok, I was not aware of this - it simplifys things, of course :smile:

**Comment by wernerjoss** [comment]
ok for the path fix :-)
but where does base_url_absolute come from  ?
(I don't see where this is computed ...)

**Pull request merged**
